name: SAM Build and Deploy

on:
  push:
    branches:
      - main


defaults:
  run:
    working-directory: ./sam_lambda/GenerateLambdaImage0508

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: aws-actions/setup-sam@v1
      - name: Build and Deploy Lambda
        with:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: eu-west-1
      - run: sam build --use-container
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name GenerateLambdaImage0508 --s3-bucket pgr301-couch-explorers --capabilities CAPABILITY_IAM --region eu-west-1
